export const events = [
  {
    id: 1,
    category: "Trivia",
    title: "Trivia Night @ Local Bar",
    details: "Wednesday · 7 PM · 5 miles away",
    saved: false,
    calendar: false,
    badge: "Local",
    icon: "🧠",
    month: 4,
    day: 22,
    weekday: "Wednesday",
  },
  {
    id: 2,
    category: "Live Music",
    title: "Outdoor Concert Series",
    details: "Friday · 6 PM · 12 miles away",
    saved: false,
    calendar: false,
    badge: "Regional",
    icon: "🎵",
    month: 4,
    day: 24,
    weekday: "Friday",
  },
  {
    id: 3,
    category: "Community",
    title: "Spring Festival",
    details: "Saturday · All Day · 8 miles away",
    saved: false,
    calendar: false,
    badge: "Local",
    icon: "🎪",
    month: 4,
    day: 25,
    weekday: "Saturday",
  },
  {
    id: 4,
    category: "Food",
    title: "Food Truck Rally",
    details: "Saturday · 1 PM · 14 miles away",
    saved: false,
    calendar: false,
    badge: "Regional",
    icon: "🍔",
    month: 4,
    day: 25,
    weekday: "Saturday",
  },
  {
    id: 5,
    category: "Sports",
    title: "Kane County Cougars Game",
    details: "Sunday · 2 PM · 11 miles away",
    saved: false,
    calendar: false,
    badge: "Local",
    icon: "⚾",
    month: 4,
    day: 26,
    weekday: "Sunday",
  },
  {
    id: 6,
    category: "Comedy",
    title: "Stand-Up Night at the Taproom",
    details: "Saturday · 8 PM · 18 miles away",
    saved: false,
    calendar: false,
    badge: "Regional",
    icon: "🎤",
    month: 4,
    day: 25,
    weekday: "Saturday",
  },
];